=== SantiagoLuqueVillanueva/ejercicioldm_ej11/file.dtd
<!ELEMENT banco (sucursal+)>
<!ELEMENT sucursal (Juan?,Marcos?,Alba?,Javi?,Lucas?,Pepe?,Alberto?)>
<!ATTLIST sucursal id NMTOKEN #REQUIRED>
<!ELEMENT Juan (#PCDATA)>
<!ELEMENT Marcos (#PCDATA)>
<!ELEMENT Alba (#PCDATA)>
<!ELEMENT Javi (#PCDATA|javi|Elena|Julia)*>
<!ELEMENT javi EMPTY>
<!ELEMENT Elena (#PCDATA)>
<!ELEMENT Julia (#PCDATA)>
<!ELEMENT Lucas (#PCDATA)>
<!ELEMENT Pepe (#PCDATA)>
<!ELEMENT Alberto (#PCDATA)>

=== SantiagoLuqueVillanueva/ejercicioldm_ej11/banco.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco SYSTEM "file.dtd">

<banco>
    <sucursal id="1">
        <cuenta:Juan>1234</cuenta:Juan>
        <cuenta:Marcos>2345</cuenta:Marcos>
        <cuenta:Alba>3456</cuenta:Alba>
    </sucursal>

    <sucursal id="2">
        <cuenta:Javi>6789</cuenta:Javi>
        <cuenta:Elena>7891</cuenta:Elena>
        <cuenta:Julia>8912</cuenta:Julia>
    </sucursal>

    <sucursal id="3">
        <cuenta:Lucas>9123</cuenta:Lucas>
        <cuenta:Pepe>1345</cuenta:Pepe>
        <cuenta:Alberto>2456</cuenta:Alberto>
    </sucursal>
</banco>
